travis:
  secure:
    BINSTAR_TOKEN: ISjffIdXdQsLZjdPpg5zBu8HDHVV993aNZDvhOGuDJtMZHAiy6QdI00cUFxAi/PuGzWd5XdapkrIvj6F8qWwF1uhYqno5TWHcVvmub5YZ6bbxUIbXOZjxJA6bpmDP4ufAt32tjc4lb2AgDRaF1t/AZ5wrfAijTRRMNMGEGIQpZyMhQR25WG/4gSFctP0mmijIh4Og1qi+nzjkOs1L5vNoyZR3Ud1mt1ZQ00ntVr8m2qscIhGK4ni9lC8sYD/nr6tsKBrQZlusnY9eubV7YEp2efsaBEcQ6qBRtyrvcpwWarIxDFs9wJ34zpU/j5Q1FsEbpb4swjv5A0Y9+WJGt3mh2ShzCdmLoHcmpuWOEBdHs62cOSr0oy2XeGNXdNohoqOSNb6BdIdFT4EE38HEeXaP2LTxCXfr6ErSdN3FsgmsUlnqDhC3yc+N7U+ZLkF6aleVosNJTun7jdc2Z0jcbZfzayWEySzG0O60PtBdnmfvlVUZvmFG3gVl4Vxgt1S+VrRm2ZBc73iu8IZfMBBxhf9Oo1wSn93cSMO8rVAV4UW5PeoLEs+iyMf7Atv2ufNBY3OzzRjdKdrPZ1fKaOiHLM/C5Uqm6i2N7IPBUVB+je9aA24sd4MVQ5Rb9qMwdl0Uw8NXSzkV9n0v2UAma96Id397KOj8/qbCVl5sAgzLIHvf34=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
